-- Enable UUID support
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Enable pgvector
CREATE EXTENSION IF NOT EXISTS vector;


-- =====================================================
-- 1. Chat Messages Table
-- =====================================================
CREATE TABLE IF NOT EXISTS public.chat_messages (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,

  user_id uuid,

  role text NOT NULL CHECK (role IN ('user', 'assistant')),

  content text NOT NULL,

  reply_to_message_id uuid REFERENCES public.chat_messages(id) ON DELETE SET NULL,

  created_at timestamptz DEFAULT now() NOT NULL
);


-- =====================================================
-- 2. Document Segments Table for RAG
-- =====================================================
CREATE TABLE IF NOT EXISTS public.doc_segments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  content text NOT NULL,

  embedding public.vector(768) NOT NULL,

  created_at timestamptz DEFAULT now() NOT NULL,

  fed_by_user_id uuid,

  chunk_index integer,

  file_path text,

  CONSTRAINT doc_segments_content_len_check CHECK (
    char_length(content) <= 20000
  ),

  CONSTRAINT doc_segments_file_path_len_check CHECK (
    file_path IS NULL OR char_length(file_path) <= 1024
  )
);


-- =====================================================
-- 3. Vector Search Function
-- =====================================================
CREATE OR REPLACE FUNCTION public.match_doc_segments(
  query_embedding vector(768),
  match_threshold float,
  match_count int
)
RETURNS TABLE (
  id bigint,
  content text,
  fed_by_user_id uuid,
  chunk_index integer,
  file_path text,
  similarity float
)
LANGUAGE sql
STABLE
AS $$
  SELECT
    ds.id,
    ds.content,
    ds.fed_by_user_id,
    ds.chunk_index,
    ds.file_path,
    1 - (ds.embedding <=> query_embedding) AS similarity
  FROM public.doc_segments ds
  WHERE 1 - (ds.embedding <=> query_embedding) > match_threshold
  ORDER BY ds.embedding <=> query_embedding
  LIMIT match_count;
$$;


-- =====================================================
-- 4. Recommended Index for Vector Search
-- =====================================================
CREATE INDEX IF NOT EXISTS doc_segments_embedding_idx
ON public.doc_segments
USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);


-- =====================================================
-- 5. Helpful Indexes
-- =====================================================
CREATE INDEX IF NOT EXISTS chat_messages_created_at_idx
ON public.chat_messages (created_at DESC);

CREATE INDEX IF NOT EXISTS doc_segments_created_at_idx
ON public.doc_segments (created_at DESC);

CREATE INDEX IF NOT EXISTS doc_segments_file_path_idx
ON public.doc_segments (file_path);
