-- =====================================================
-- 1. Extensions & Setup
-- =====================================================
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS vector;

-- Create Roles Enum
DO $$ BEGIN
    CREATE TYPE user_role AS ENUM ('admin', 'user');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- =====================================================
-- 2. Profiles Table (User Management)
-- =====================================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email text,
  role user_role DEFAULT 'user' NOT NULL,
  updated_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Policies for Profiles
CREATE POLICY "Public profiles are viewable by everyone" 
ON public.profiles FOR SELECT USING (true);

CREATE POLICY "Users can update own profile" 
ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Trigger to automatically create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role)
  VALUES (new.id, new.email, 'user');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- =====================================================
-- 3. Documents Table (Knowledge Base Meta)
-- =====================================================
CREATE TABLE IF NOT EXISTS public.documents (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  title text NOT NULL,
  description text,
  category text DEFAULT 'General',
  tags text[],
  file_type text,
  file_url text,
  status text DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_by text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- Enable RLS for Documents
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;

-- Policies for Documents
CREATE POLICY "Documents are viewable by authenticated users" 
ON public.documents FOR SELECT TO authenticated USING (true);

CREATE POLICY "Only admins can modify documents" 
ON public.documents FOR ALL TO authenticated 
USING (
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid() AND role = 'admin'
  )
);

-- =====================================================
-- 4. Chat Messages Table
-- =====================================================
CREATE TABLE IF NOT EXISTS public.chat_messages (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES auth.users,
  role text NOT NULL CHECK (role IN ('user', 'assistant')),
  content text NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can see their own chat history"
ON public.chat_messages FOR SELECT TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own messages"
ON public.chat_messages FOR INSERT TO authenticated
WITH CHECK (auth.uid() = user_id);

-- =====================================================
-- 5. Document Segments (RAG Table)
-- =====================================================
CREATE TABLE IF NOT EXISTS public.doc_segments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id uuid REFERENCES public.documents(id) ON DELETE CASCADE,
  content text NOT NULL,
  embedding public.vector(768) NOT NULL, -- Match your embedding model dimensions
  created_at timestamptz DEFAULT now() NOT NULL,
  chunk_index integer,
  
  CONSTRAINT doc_segments_content_len_check CHECK (char_length(content) <= 20000)
);

-- =====================================================
-- 6. Vector Search Function
-- =====================================================
CREATE OR REPLACE FUNCTION public.match_doc_segments(
  query_embedding vector(768),
  match_threshold float,
  match_count int
)
RETURNS TABLE (
  id bigint,
  content text,
  document_id uuid,
  chunk_index integer,
  similarity float
)
LANGUAGE sql
STABLE
AS $$
  SELECT
    ds.id,
    ds.content,
    ds.document_id,
    ds.chunk_index,
    1 - (ds.embedding <=> query_embedding) AS similarity
  FROM public.doc_segments ds
  JOIN public.documents d ON d.id = ds.document_id
  WHERE d.status = 'active' -- Only search enabled documents
    AND 1 - (ds.embedding <=> query_embedding) > match_threshold
  ORDER BY ds.embedding <=> query_embedding
  LIMIT match_count;
$$;

-- =====================================================
-- 7. Indexes
-- =====================================================
CREATE INDEX IF NOT EXISTS doc_segments_embedding_idx
ON public.doc_segments USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

CREATE INDEX IF NOT EXISTS chat_messages_created_at_idx ON public.chat_messages (created_at DESC);
CREATE INDEX IF NOT EXISTS documents_created_at_idx ON public.documents (created_at DESC);
