-- =====================================================
-- 1. Extensions
-- =====================================================
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS vector;


-- =====================================================
-- 2. Drop Old Function First
-- Prevent: cannot change return type of existing function
-- =====================================================
DROP FUNCTION IF EXISTS public.match_doc_segments(vector, float, int);


-- =====================================================
-- 3. Profiles Table
-- User Management + Role
-- =====================================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email text,
  role text DEFAULT 'user' CHECK (role IN ('admin', 'user')),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;


-- Drop old policies first to prevent duplicate policy error
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile." ON public.profiles;
DROP POLICY IF EXISTS "Admins can update all profiles." ON public.profiles;


CREATE POLICY "Public profiles are viewable by everyone."
ON public.profiles
FOR SELECT
USING (true);


CREATE POLICY "Users can update own profile."
ON public.profiles
FOR UPDATE
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);


CREATE POLICY "Admins can update all profiles."
ON public.profiles
FOR UPDATE
USING (
  EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE profiles.id = auth.uid()
    AND profiles.role = 'admin'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE profiles.id = auth.uid()
    AND profiles.role = 'admin'
  )
);


-- =====================================================
-- 4. Documents Table
-- Metadata for Admin CRUD
-- =====================================================
CREATE TABLE IF NOT EXISTS public.documents (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,

  title text NOT NULL,
  description text,
  category text DEFAULT 'General',
  tags text[] DEFAULT '{}',

  file_type text,
  file_url text,
  file_path text,

  status text DEFAULT 'active' CHECK (status IN ('active', 'inactive')),

  created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,

  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;


DROP POLICY IF EXISTS "Admins have full access to documents" ON public.documents;
DROP POLICY IF EXISTS "Users can view active documents" ON public.documents;


CREATE POLICY "Admins have full access to documents"
ON public.documents
FOR ALL
USING (
  EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE profiles.id = auth.uid()
    AND profiles.role = 'admin'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE profiles.id = auth.uid()
    AND profiles.role = 'admin'
  )
);


CREATE POLICY "Users can view active documents"
ON public.documents
FOR SELECT
USING (status = 'active');


-- =====================================================
-- 5. Document Segments Table
-- RAG Vector Chunks
-- =====================================================
CREATE TABLE IF NOT EXISTS public.doc_segments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  document_id uuid REFERENCES public.documents(id) ON DELETE CASCADE,

  content text NOT NULL,
  embedding public.vector(768) NOT NULL,

  chunk_index integer,

  created_at timestamptz DEFAULT now() NOT NULL,

  CONSTRAINT doc_segments_content_len_check CHECK (
    char_length(content) <= 20000
  )
);

ALTER TABLE public.doc_segments ENABLE ROW LEVEL SECURITY;


DROP POLICY IF EXISTS "Admins have full access to doc segments" ON public.doc_segments;
DROP POLICY IF EXISTS "Users can view active document segments" ON public.doc_segments;


CREATE POLICY "Admins have full access to doc segments"
ON public.doc_segments
FOR ALL
USING (
  EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE profiles.id = auth.uid()
    AND profiles.role = 'admin'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE profiles.id = auth.uid()
    AND profiles.role = 'admin'
  )
);


CREATE POLICY "Users can view active document segments"
ON public.doc_segments
FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM public.documents d
    WHERE d.id = doc_segments.document_id
    AND d.status = 'active'
  )
);


-- =====================================================
-- 6. Vector Search Function
-- No room_id
-- No source_message_id
-- Search only active documents
-- =====================================================
CREATE OR REPLACE FUNCTION public.match_doc_segments(
  query_embedding vector(768),
  match_threshold float,
  match_count int
)
RETURNS TABLE (
  id bigint,
  content text,
  document_id uuid,
  document_title text,
  category text,
  similarity float
)
LANGUAGE sql
STABLE
AS $$
  SELECT
    ds.id,
    ds.content,
    ds.document_id,
    d.title AS document_title,
    d.category,
    1 - (ds.embedding <=> query_embedding) AS similarity
  FROM public.doc_segments ds
  JOIN public.documents d ON ds.document_id = d.id
  WHERE d.status = 'active'
    AND 1 - (ds.embedding <=> query_embedding) > match_threshold
  ORDER BY ds.embedding <=> query_embedding
  LIMIT match_count;
$$;


-- =====================================================
-- 7. Chat Messages Table
-- User chats with BEN AI
-- =====================================================
CREATE TABLE IF NOT EXISTS public.chat_messages (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,

  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,

  role text NOT NULL CHECK (role IN ('user', 'assistant')),

  content text NOT NULL,

  reply_to_message_id uuid REFERENCES public.chat_messages(id) ON DELETE SET NULL,

  created_at timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;


DROP POLICY IF EXISTS "Users can see only their own messages" ON public.chat_messages;
DROP POLICY IF EXISTS "Users can insert their own messages" ON public.chat_messages;
DROP POLICY IF EXISTS "Users can delete their own messages" ON public.chat_messages;


CREATE POLICY "Users can see only their own messages"
ON public.chat_messages
FOR SELECT
USING (auth.uid() = user_id);


CREATE POLICY "Users can insert their own messages"
ON public.chat_messages
FOR INSERT
WITH CHECK (auth.uid() = user_id);


CREATE POLICY "Users can delete their own messages"
ON public.chat_messages
FOR DELETE
USING (auth.uid() = user_id);


-- =====================================================
-- 8. Auto Create Profile When User Signs Up
-- =====================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (
    id,
    email,
    role
  )
  VALUES (
    NEW.id,
    NEW.email,
    'user'
  )
  ON CONFLICT (id) DO NOTHING;

  RETURN NEW;
END;
$$;


DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;


CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE PROCEDURE public.handle_new_user();


-- =====================================================
-- 9. Updated At Trigger Function
-- =====================================================
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;


DROP TRIGGER IF EXISTS set_profiles_updated_at ON public.profiles;
CREATE TRIGGER set_profiles_updated_at
BEFORE UPDATE ON public.profiles
FOR EACH ROW
EXECUTE PROCEDURE public.set_updated_at();


DROP TRIGGER IF EXISTS set_documents_updated_at ON public.documents;
CREATE TRIGGER set_documents_updated_at
BEFORE UPDATE ON public.documents
FOR EACH ROW
EXECUTE PROCEDURE public.set_updated_at();


-- =====================================================
-- 10. Indexes
-- =====================================================
CREATE INDEX IF NOT EXISTS documents_status_idx
ON public.documents (status);


CREATE INDEX IF NOT EXISTS documents_created_by_idx
ON public.documents (created_by);


CREATE INDEX IF NOT EXISTS documents_created_at_idx
ON public.documents (created_at DESC);


CREATE INDEX IF NOT EXISTS doc_segments_document_id_idx
ON public.doc_segments (document_id);


CREATE INDEX IF NOT EXISTS chat_messages_user_id_idx
ON public.chat_messages (user_id);


CREATE INDEX IF NOT EXISTS chat_messages_created_at_idx
ON public.chat_messages (created_at DESC);


-- Vector index
-- Recommended after you have inserted some rows
CREATE INDEX IF NOT EXISTS doc_segments_embedding_idx
ON public.doc_segments
USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);
