-- =====================================================
-- 1. Extensions & Handlers
-- =====================================================
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS vector;

-- Drop function first to prevent "cannot change return type" error
DROP FUNCTION IF EXISTS public.match_doc_segments(vector, float, int);

-- =====================================================
-- 2. Profiles Table (User Management)
-- =====================================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email text,
  role text DEFAULT 'user' CHECK (role IN ('admin', 'user')),
  updated_at timestamptz DEFAULT now()
);

-- Enable RLS on Profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles
  FOR SELECT USING (true);

CREATE POLICY "Users can update own profile." ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- =====================================================
-- 3. Documents Table (Metadata for CRUD)
-- =====================================================
CREATE TABLE IF NOT EXISTS public.documents (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  title text NOT NULL,
  description text,
  category text DEFAULT 'General',
  tags text[],
  file_type text,
  file_url text,
  status text DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_by text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;

-- Admin can do everything, Users can only Read active ones
CREATE POLICY "Admins have full access to documents" ON public.documents
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
  );

CREATE POLICY "Users can view active documents" ON public.documents
  FOR SELECT USING (status = 'active');

-- =====================================================
-- 4. Document Segments Table (RAG Vectors)
-- =====================================================
CREATE TABLE IF NOT EXISTS public.doc_segments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id uuid REFERENCES public.documents(id) ON DELETE CASCADE,
  content text NOT NULL,
  embedding public.vector(768) NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  chunk_index integer
);

-- =====================================================
-- 5. Vector Search Function (Fixed)
-- =====================================================
CREATE OR REPLACE FUNCTION public.match_doc_segments(
  query_embedding vector(768),
  match_threshold float,
  match_count int
)
RETURNS TABLE (
  id bigint,
  content text,
  document_id uuid,
  similarity float
)
LANGUAGE sql
STABLE
AS $$
  SELECT
    ds.id,
    ds.content,
    ds.document_id,
    1 - (ds.embedding <=> query_embedding) AS similarity
  FROM public.doc_segments ds
  JOIN public.documents d ON ds.document_id = d.id
  WHERE d.status = 'active' 
    AND 1 - (ds.embedding <=> query_embedding) > match_threshold
  ORDER BY ds.embedding <=> query_embedding
  LIMIT match_count;
$$;

-- =====================================================
-- 6. Chat Messages Table
-- =====================================================
CREATE TABLE IF NOT EXISTS public.chat_messages (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid DEFAULT auth.uid(),
  role text NOT NULL CHECK (role IN ('user', 'assistant')),
  content text NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can see only their own messages" ON public.chat_messages
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own messages" ON public.chat_messages
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- =====================================================
-- 7. Automated Profile Creation Trigger
-- =====================================================
-- This creates a profile record automatically when someone signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role)
  VALUES (new.id, new.email, 'user');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
